### ISSUE TITLE
Add types-setuptools as dependency

### ISSUE THREAD

**Issue by JanJaguschQC** [Quantco/pre-commit-mirrors-mypy#4]
Using this pre-commit hook I'm getting the following error:

```sh
error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.10)
note: Hint: "python3 -m pip install types-setuptools"
note: (or run "mypy --install-types" to install all missing stub packages)
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I could resolve the error by installing `types-setuptools` into the environment.

**Comment by JanJaguschQC** [comment]
It's probably better to provide this as an `additional_dependency`.

**Comment by xhochy** [comment]
> It's probably better to provide this as an `additional_dependency`.

Yes, depending on your code you will nowadays need a larger set of these types packages.
